### ISSUE TITLE
HC16 checklist

### ISSUE THREAD

**Issue by jpata** [jpata/tthbb13#84]
This is a checklist of what we'd like in for a HC16 result, planning to go for pre-app in mid-September.

tools:
- [x] basic data/mc validation: work on updated python sparsinator https://github.com/jpata/tthbb13/issues/83
- [x] data lumi from DAS: https://github.com/jpata/tthbb13/issues/94
- [x] local high-efficiency MEAnalysis workflow: https://github.com/jpata/tthbb13/issues/100
- [x] update limit setting tools (https://github.com/jpata/tthbb13/issues/90)

scale factors:
- [x] update btag SF to post-ICHEP  https://github.com/vhbb/cmssw/issues/521
- [ ] electron SF https://github.com/vhbb/cmssw/issues/495

validations:
- [ ] new btag SF
- [x] muon SF from Gael https://github.com/vhbb/cmssw/pull/516
- [x] HIP mitigated btag https://github.com/vhbb/cmssw/pull/530

results:
- [x] V24 vhbb ntuples: https://github.com/vhbb/cmssw/issues/509
- [x] updated TF & btagPDF for V24
- [x] rerun V24 ntuples with MEM and full syst
- [x] integrate FH plots
- [x] re-enable JES/JER syst
- [x] run dummy limits (BLR only)
- [ ] rerun baseline limits
- [ ] cMVAv2 category limits
- [ ] develop smart categorization
- [ ] smart category limits
- [ ] HIP validation
- [ ] Check data/MC plots for MEM
- [ ] Understand top tagger distributions
- [ ] Define more control regions and test variables
- [ ] Define single and double boosted categories
- [ ] Mass of ttH-top in control regions
- [ ] Are we affected by HIP?
- [X] Retrain Multiclass on all 6j events, not just 6/4. 
- [ ] Check effects of weights (PU, btag, ..) on multiclass
- [ ] Revisit substructure calibrations

**Comment by jpata** [comment]
I've reran the no-ME ntuples last night: [Aug11_leptonic_nome_v1](http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=Joosep+Pata&refresh=60&table=Mains&p=1&records=-1&activemenu=1&pattern=*Aug11_leptonic_nome_v1*&task=&from=&till=&timerange=lastMonth)

**Comment by jpata** [comment]
Submitting a few MEM test jobs: `Aug16_testing_withme_v1`

**Comment by jpata** [comment]
Submitted MEM on MC: [Aug17_leptonic_v1](http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=Joosep+Pata&refresh=60&table=Mains&p=1&records=-1&activemenu=1&pattern=*Aug17_leptonic_v1*&task=&from=&till=&timerange=lastMonth)
